# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author_notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='submission',
            name='editor_notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
