# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20160731_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unassessed'), (1, 'Shortlisted'), (2, 'Rejected'), (3, 'Accepted')], default=0),
        ),
    ]
