# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
