# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
