# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:59
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from=models.IntegerField(verbose_name='issue number'), unique=True),
            preserve_default=False,
        ),
    ]
