# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='slug',
        ),
    ]
