# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20160719_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='issues.Author'),
            preserve_default=False,
        ),
    ]
