# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('bio', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='issue publication date')),
                ('number', models.IntegerField(verbose_name='issue number')),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(blank=True, upload_to='cover_image_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='story_uploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Author')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Issue')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
