# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='submission_timestamp',
        ),
        migrations.AddField(
            model_name='issue',
            name='introduction',
            field=models.TextField(default='', max_length=500),
        ),
    ]
