# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160719_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_image_uploads/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
