# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160719_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='author',
        ),
    ]
