# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_story_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('bio', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='introduction',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
