# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 17:41
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20160801_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False, populate_from=journal.models.autoslug_populate_from, slugify=journal.models.autoslug_slugify, unique_with=['author__first_name', 'author__last_name']),
            preserve_default=False,
        ),
    ]
