# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='issue as an epub document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='issue as PDF document'),
        ),
    ]
