# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-28 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_issue_mobi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True, max_length=30000),
        ),
    ]
