# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20160722_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitter',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='submitter',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
