# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_story_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bandcamp_album',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
