# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_issue_bandcamp_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='bandcamp_album',
            field=models.IntegerField(blank=True),
        ),
    ]
