# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20170527_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='bandcamp_album',
            new_name='bandcamp_album_number',
        ),
        migrations.AddField(
            model_name='issue',
            name='bandcamp_album_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
