# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_story_bandcamp_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='bandcamp_album_number',
            new_name='bandcamp_album_id',
        ),
    ]
