# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20170527_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='bandcamp_track_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
