# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-31 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_auto_20170528_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='bandcamp_track_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
