# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_auto_20170531_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='bandcamp_album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
