# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_auto_20190505_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
