# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Submission_Guidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': 'Submission Guidelines',
            },
        ),
    ]
