# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-11 19:39
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_auto_20170611_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission_guidelines',
            name='submissions',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
