# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-05 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
    ]
